development:
  adapter: postgresql
  encoding: unicode
  database: guitar_shop_development
  username: postgres
  password: postgres
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: guitar_shop_production
  username: postgres
  password: postgres
  pool: 5
